### ISSUE TITLE
Insecure Content being served on HTTP

### ISSUE THREAD

**Issue by tanmaymohan** [BitsPleaseMSI/achievement-ms-frontend#1]
The site is being served on HTTPS but the images and other assets are being fetched from a AWS IP which is being served over HTTP. Also visiting the IP lists all the images in directory listing page which is insecure way of storing the files.

Some URLs to be fixed : 

http://13.59.95.13:8081/ (Read more here at  : https://www.chromestatus.com/feature/5629709824032768) 

https://amsmsi.com/achievements/all

**Comment by sreejeet** [comment]
The insecure image hosting is a temporary back-end issue and poses no major threat. It will be resolved once the project is officially funded.

As for this URL "https://amsmsi.com/achievements/all", it is a public API. All the information is freely available and can be used for any new / existing client side application development.
